server:
    port: 8081
spring:
    application:
        name: fraud
    datasource:
        password: password
        url: jdbc:postgresql://localhost:5432/fraud
        username: axel
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: true
eurkea:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        fetch-registery: true
        register-with-eureka: true